name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/dockerfile --tag edot99/midterm_task
    - name: Push the image to DockerHub
      run: docker login -u EdoT99 -p ${{ secrets.DOCKER_TOKEN }} && docker push EdoT99/midterm_task
